[[headers]]
for = "/*"
[headers.values]
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy= " midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=()"
  Referrer-Policy = "strict-origin-when-cross-origin"