name: Import Movies

on:
  push:
    branches:
      - 'main'

  schedule:
    - cron:  '15 5,17 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert_feeds:
    name: Convert Feeds
    runs-on: ubuntu-latest

    steps:

      - name: Checkout latest copy of the site
        uses: actions/checkout@v2

      - name: Process the Letterboxd feed list
        uses: funkylarma/rss-feed-to-markdown@main
        with:
          feed_url: 'https://letterboxd.com/funkylarma/rss/'
          template_file: './includes/templates/letterboxd.md'
          output_dir: 'src/media/'
          date_format: 'yyyy-MM-dd'

      - name: Commit and push any new movie watches
        run: |
            git config --global user.email "funkylarma@users.noreply.github.com"
            git config --global user.name "funkylarma via GitHub Actions"
            git add 'src/media/**/*.md'
            git diff --quiet && git diff --staged --quiet || git commit -am "New movie watches added - Automated"
            git push
