name: Import Photos

on:
  push:
    branches:
      - "main"

  schedule:
    - cron: "0 5,17 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert_feeds:
    name: Convert Feeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest copy of the site
        uses: actions/checkout@v2

      - name: Process the Pixelfed feed list
        uses: funkylarma/processPhotos@main

      - name: Commit and push any new photos
        run: |
          git config --global user.email "funkylarma@users.noreply.github.com"
          git config --global user.name "funkylarma via GitHub Actions"
          git add 'src/photos/**/*.md'
          git diff --quiet && git diff --staged --quiet || git commit -am "New photos added - Automated"
          git push
