name: Build new Markdown Posts from RSS Feeds

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: |
            echo "::set-output name=year::$(date +'%Y')"
            echo "::set-output name=month::$(date +'%m')"
            echo "::set-output name=day::$(date +'%d')"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run RSS Feed to Markdown Action for Letterboxd Feed
        uses: funkylarma/rss-feed-to-markdown@main
        with:
          feed_url: 'https://letterboxd.com/funkylarma/rss/'
          template_file: './includes/templates/letterboxd.md'
          output_dir: 'src/media/'
          date_format: 'yyyy-MM-dd HH:mm:ss'

      - name: Run RSS Feed to Markdown Action for Feedbin Feed
        uses: funkylarma/rss-feed-to-markdown@main
        with:
          feed_url: 'https://feedbin.com/starred/9e06fb0a995c4178a5b8f0194f7dc433.xml'
          template_file: './includes/templates/feedbin.md'
          output_dir: 'src/likes/'
          date_format: 'yyyy-MM-dd HH:mm:ss xx'

      - name: Commit and Push new likes
        run: |
            git config --global user.email "funkylarma@users.noreply.github.com"
            git config --global user.name "funkylarma via GitHub Actions"
            git add 'src/media/**/*.md'
            git add 'src/likes/**/*.md'
            git commit -am "new posts added - automated"
            git push
